"""Adicionando Foreing Key

Revision ID: 1ae398ca237a
Revises: 7fe4480e4265
Create Date: 2023-10-04 16:08:50.019956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae398ca237a'
down_revision: Union[str, None] = '7fe4480e4265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_usuario', 'users', ['user_id'], ['_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuario', type_='foreignkey')

    # ### end Alembic commands ###
