"""Adding Orders

Revision ID: 7aa00a07bbc7
Revises: 84e2f8eb52c9
Create Date: 2023-10-10 14:03:12.737315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa00a07bbc7'
down_revision: Union[str, None] = '84e2f8eb52c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
